name: vaul_sim_ws_${USER:-default}

services:
  devkit:
    image: vaul_sim_ws-devkit
    build:
      context: .
      dockerfile: devkit.Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    command: sleep infinity
    depends_on:
      - simulator
    networks:
      - simulation
    volumes:
      - ../../dev_ws:/home/ros_dev/ws:cached,z
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      FOXGLOVE_PORT: ${FOXGLOVE_PORT:-8765}
    userns_mode: ${USERNS_MODE:-}

  simulator:
    image: ghcr.io/vaul-ulaval/f1tenth_gym_ros:latest
    entrypoint: ["/bin/bash", "-c"]
    command:
      - "source /opt/ros/humble/setup.bash && source /sim_ws/install/local_setup.bash && exec ros2 launch f1tenth_gym_ros gym_bridge_launch.py"
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      FOXGLOVE_PORT: ${FOXGLOVE_PORT:-8765}
    ports:
      - "${FOXGLOVE_PORT:-8765}:8765"
    networks:
      - simulation

networks:
  simulation:
    driver: bridge